Add docker package for generation of jwks.json config
SkynetLabs/ansiblecm pull request #9
Opened 2022-07-22 07:19 UTC by firyx

# PULL REQUEST

## Overview

Install docker package inside Ansible Control Machine so that we can use `docker run ...` commands directly (not only via `docker_container` module) in playbooks (e.g. for `jwks.json` generation).

## Example for Visual Changes

## Checklist

- [x] All git commits are signed. (REQUIRED)
- [x] All new methods or updated methods have clear docstrings.
- [x] Testing added or updated for new methods.
- [x] Verified if any changes impact the WebPortal Health Checks.
- [x] Appropriate documentation updated.
- [ ] Changelog file created.

## Issues Closed

2022-07-22 08:30 UTC, kwypchlo requested changes
we already install docker via pip https://github.com/SkynetLabs/ansiblecm/blob/master/Dockerfile#L43

2022-09-09 10:56 UTC, kwypchlo commented
@firyx is this pull request still relevant?

2022-09-20 10:40 UTC, firyx commented
> we already install docker via pip https://github.com/SkynetLabs/ansiblecm/blob/master/Dockerfile#L43

Via pip we install docker SDK for Python so that Ansible can drive docker (on remote hosts).
Via apk we install docker so that we can run docker commands (locally).

2022-09-20 10:41 UTC, kwypchlo approved these changes

2022-09-20 10:41 UTC, merged